{{ if .Values.nifi.authentication.ldap.manager_password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "nifi.fullname" . }}
  labels:
    app: {{ include "nifi.name" . | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
{{ if .Values.nifi.authentication.ldap.manager_password }}
    ldap_manager_password: {{ .Values.nifi.authentication.ldap.manager_password | b64enc | quote }}
{{ end }}
{{ end }}