apiVersion: v1
kind: Secret
metadata:
  name: {{ template "certs.fullname" . }}
  labels:
    app: {{ include "certs.name" . | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  {{ $ca_certificate_path := printf "%s/%s" .Values.dir .Values.ca_certificate }}
  ca_certificate: {{ (.Files.Get $ca_certificate_path) | b64enc | quote }}
  {{ $admin_certificate := printf "%s/%s" .Values.dir .Values.admin_user.certificate }}
  admin_certificate: {{ (.Files.Get $admin_certificate) | b64enc | quote }}
  {{ $admin_private_key := printf "%s/%s" .Values.dir .Values.admin_user.private_key }}
  admin_private_key: {{ (.Files.Get $admin_private_key) | b64enc | quote }}
  node_certs: |-
{{- $files := .Files -}}
{{- $certificate_dir := .Values.dir -}}
{{- range .Values.node_certs -}}
  {{- $node_private_key := printf "%s/%s" $certificate_dir .private_key -}}
  {{- $node_certificate := printf "%s/%s" $certificate_dir .certificate }}
  node_{{ .node }}_private_key: {{ ($files.Get $node_private_key) | b64enc | quote }}
  node_{{ .node }}_certificate: {{ ($files.Get $node_certificate) | b64enc | quote }}
{{- end }}