nifi:
  properties:
    secured: true
  certificate_source:
    nifi_toolkit: true
  authentication:
    ldap:
      enabled: true
      authentication_strategy: "SIMPLE"
      referral_strategy: "FOLLOW"
      identity_strategy: "USE_USERNAME"
      url: ""
      manager_dn: ""
      manager_password: ""
      connect_timeout: "10 secs"
      read_timeout: "10 secs"
      user_search_base: ""
      user_search_filter: ""
      expiration_period: "12 hours"
  authorization:
    ldap:
      admin_user_cn: ""
      enforce_case_sensitivity: "false"
      sync_interval: "1 mins"
      page_size: ""
      user_object_class: ""
      user_search_filter: ""
      user_search_scope: "ONE_LEVEL"
      user_identity_attribute: "cn"
      user_group_name_attribute: ""
      user_referenced_group_attribute: ""
      group_search_base: ""
      group_object_class: ""
      group_search_scope: "ONE_LEVEL"
      group_search_filter: ""
      group_name_attribute: "cn"
      group_member_attribute: ""
      group_referenced_user_attribute: ""